services:
  web:
    build:
      path: .
      manifest: ./dockerfiles/web/Dockerfile
    command: gunicorn scrimmage:app -w 4 -b 0.0.0.0:8000
    domain: scrimmage.pokerbots.org
    environment:
      - PRODUCTION=True
      - SQLALCHEMY_DATABASE_URI
      - CELERY_BROKER_URL
      - SECRET_KEY
      - AUTH_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_REGION
      - S3_BUCKET
    port: 8000
    scale:
      cpu: 512
      memory: 512
  worker:
    build:
      path: .
      manifest: ./dockerfiles/worker/Dockerfile
    command: celery -A scrimmage.celery_app worker --loglevel=info --concurrency=1
    environment:
      - PRODUCTION=True
      - SQLALCHEMY_DATABASE_URI
      - CELERY_BROKER_URL
      - SECRET_KEY
      - AUTH_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_REGION
      - S3_BUCKET
    scale:
      cpu: 1024
      memory: 1536
  flower:
    build:
      path: .
      manifest: ./dockerfiles/web/Dockerfile
    command: flower -A scrimmage.celery_app --address=0.0.0.0
    domain: flower.pokerbots.org
    environment:
      - PRODUCTION=True
      - SQLALCHEMY_DATABASE_URI
      - CELERY_BROKER_URL
      - SECRET_KEY
      - FLOWER_BASIC_AUTH
    port: 5555
    scale:
      cpu: 256
      memory: 512
