"""Add challenger and opponent score

Revision ID: 1ce0eb6f5f54
Revises: d172bd5e57c1
Create Date: 2019-01-03 18:42:42.514602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce0eb6f5f54'
down_revision = 'd172bd5e57c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('challenger_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('opponent_score', sa.Integer(), nullable=True))
    op.add_column('tournament_games', sa.Column('bot_a_score', sa.Integer(), nullable=True))
    op.add_column('tournament_games', sa.Column('bot_b_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_games', 'bot_b_score')
    op.drop_column('tournament_games', 'bot_a_score')
    op.drop_column('games', 'opponent_score')
    op.drop_column('games', 'challenger_score')
    # ### end Alembic commands ###
