"""Add elo margins

Revision ID: 1ce6401d9b77
Revises: 2fef83bf977e
Create Date: 2019-01-21 21:02:22.495574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce6401d9b77'
down_revision = '2fef83bf977e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_bots', sa.Column('elo_minus_margin', sa.Float(), nullable=True))
    op.add_column('tournament_bots', sa.Column('elo_plus_margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_bots', 'elo_plus_margin')
    op.drop_column('tournament_bots', 'elo_minus_margin')
    # ### end Alembic commands ###
