"""Settings values are not unique

Revision ID: 44ee25bd682b
Revises: 7fcc09cee318
Create Date: 2019-01-21 17:57:03.328096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ee25bd682b'
down_revision = '7fcc09cee318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settings_value', table_name='settings')
    op.create_index(op.f('ix_settings_value'), 'settings', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_value'), table_name='settings')
    op.create_index('ix_settings_value', 'settings', ['value'], unique=1)
    # ### end Alembic commands ###
