"""Add challenger and opponent log uploads

Revision ID: 6ef8ada19388
Revises: fb00f6d8fded
Create Date: 2018-12-31 09:55:16.155439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef8ada19388'
down_revision = 'fb00f6d8fded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('challenger_log_s3_key', sa.String(length=256), nullable=True))
    op.add_column('games', sa.Column('opponent_log_s3_key', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'opponent_log_s3_key')
    op.drop_column('games', 'challenger_log_s3_key')
    # ### end Alembic commands ###
