"""Add is_disabled field to bots

Revision ID: 7fcc09cee318
Revises: 69a829b740bf
Create Date: 2019-01-10 11:20:34.177961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcc09cee318'
down_revision = '69a829b740bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('is_disabled', sa.Boolean(), nullable=False, server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'is_disabled')
    # ### end Alembic commands ###
