"""Add json statistics to tournament games

Revision ID: 8e2c5b166767
Revises: 1ce6401d9b77
Create Date: 2019-01-28 22:07:29.436073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2c5b166767'
down_revision = '1ce6401d9b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_games', sa.Column('json_statistics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_games', 'json_statistics')
    # ### end Alembic commands ###
