"""Add private tournament flag

Revision ID: b23360aea6f7
Revises: 8e2c5b166767
Create Date: 2019-01-28 22:22:48.383614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23360aea6f7'
down_revision = '8e2c5b166767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_private')
    # ### end Alembic commands ###
