"""Remove elo field from tournament games (if this doesn't work read this file)

Revision ID: be27713baea3
Revises: 4b3121fe5023
Create Date: 2019-01-21 19:54:56.520001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be27713baea3'
down_revision = '4b3121fe5023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_games', 'bot_a_elo')
    op.drop_column('tournament_games', 'bot_b_elo')

    # If you are reading this during your first pull of the repo, run the following instead:
    # - python manage.py shell
    #       # from scrimmage import db
    #       # db.create_all()
    # - python manage.py db heads
    # - python manage.py db stamp <the revision ID from above>


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_games', sa.Column('bot_b_elo', sa.FLOAT(), nullable=True))
    op.add_column('tournament_games', sa.Column('bot_a_elo', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
