"""Add create time and title to announcements table

Revision ID: e7c5d6a3fd01
Revises: 3a0f6296d6d5
Create Date: 2018-12-27 15:03:48.057915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c5d6a3fd01'
down_revision = '3a0f6296d6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('announcements', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'create_time')
    op.drop_column('announcements', 'title')
    # ### end Alembic commands ###
