"""Add team join requests table

Revision ID: fb00f6d8fded
Revises: e7c5d6a3fd01
Create Date: 2018-12-27 23:37:54.871284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb00f6d8fded'
down_revision = 'e7c5d6a3fd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kerberos', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_kerberos'), 'join_requests', ['kerberos'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_join_requests_kerberos'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
